dependencies:
  # to download dependencies from github
  # - <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1

compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1"
# Uncomment to deploy in a real network (test or not)
# dotenv: .env

# wallets:
#   from_key: ${PRIVATE_KEY}

networks:
  development:
    keyhash: "0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311"
    fee: 100000000000000000 # 0.1 * 10**18

  rinkeby:
    eth_usd_price_feed: "0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e"


  # For use this network we have to create an account in (alchemy)[]
  # There, we have to create a new app and take its http url
  # After that, we can run the next command to create our new network 
  #     
  # Be careful, we shouldn't have a network with the same name
  # 
  # ```bash
  # brownie networks add development mainnet-fork-dev cmd=ganache-cli \ 
  #   host=http://127.0.0.1 fork= {{http/alchemy/app}} \ 
  #   accounts=10 mnemonic=brownie port=8545
  # ```

  mainnet-fork-dev:
    eth_usd_price_feed: "0x5f4ec3df9cbd43714fe2740f5e3616155c5b8419"

app_config:
  minimal_usd_fee: 50