dependencies:
  # to download dependencies from github
  # - <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1

compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1"
# Uncomment to deploy in a real network (test or not)
# dotenv: .env

# wallets:
#   from_key: ${PRIVATE_KEY}

networks:
  development:
    keyhash: "0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311"
    fee: 100000000000000000 # 0.1 * 10**18

  rinkeby:
    eth_usd_price_feed: "0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e"

  mainnet-fork:
    eth_usd_price_feed: "0x5f4ec3df9cbd43714fe2740f5e3616155c5b8419"
