dependencies:
  # to download dependencies from github
  # - <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1

compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1"
# Uncomment to deploy in a real network (test or not)
# dotenv: .env

# wallets:
#   from_key: ${PRIVATE_KEY}

networks:
  rinkeby:
    eth_usd_price_feed: "0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e"

  mainnet-fork-dev: # test network from  alchemy.com
    eth_usd_price_feed: "0x5f4ec3df9cbd43714fe2740f5e3616155c5b8419"
